version: '3'

services:
  storeserver:
    build: ..
    restart: always
    ports:
      - 3001:3001
    env_file:
      - variables.env
    links:
      - mongo

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo/db/:/data/db/
      - ./mongo/log/:/var/log/mongodb/
    env_file:
      - variables.env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - variables.env
    links:
      - mongo
